### ISSUE TITLE
手动认证是不是要调用自己平台的登录接口？

### ISSUE THREAD

**Issue by stephenwang1011** [ztosec/secscan-authcheck#6]
如题，我手动录入了认证信息，保存之后并且start了，查看流量并且开启监听，浏览我指定的网页没有流量 不知道哪里设置有误 请指出 谢谢
![image](https://user-images.githubusercontent.com/3350356/67375545-5d9d8200-f5b5-11e9-93cc-3d7d7213a380.png)

**Comment by rzte** [comment]
配错了
hosts：想要捕获的请求头中的host，若有多个以`,`分隔
url-pattern: 完整的正则匹配，一般默认 `.*` 即可

**Comment by stephenwang1011** [comment]
您好，经过我修改之后 完全搞定了，感谢，修改如下：
hosts: 去掉http://
url-pattern：按照您说的 使用的是.*默认匹配的
感谢 确实是个好工具 我再研究下
![image](https://user-images.githubusercontent.com/3350356/67379949-36967e80-f5bc-11e9-95c6-c03313ae7028.png)
