### ISSUE TITLE
手动录入的认证信息（不同角色账户）在流量明细里面token的value是一致的，是怎么回事？

### ISSUE THREAD

**Issue by stephenwang1011** [ztosec/secscan-authcheck#7]
您好，作者：
   我是手动录入的不同角色的认证信息，
第一个是普通角色：
![image](https://user-images.githubusercontent.com/3350356/67400145-d0bbee00-f5df-11e9-82d8-62221a03e517.png)

第二个是管理员角色的信息，这里就不在截图了，和原始包的登录用户名和密码一致。

但是我在流量明细里面看到 请求不同的请求，  request里面的 token都是一样（都是管理员账户的token）：
原始包token:
![image](https://user-images.githubusercontent.com/3350356/67400354-1c6e9780-f5e0-11e9-845a-1d8d822b5555.png)

普通用户的token:
![image](https://user-images.githubusercontent.com/3350356/67400390-28f2f000-f5e0-11e9-80f2-c9f437cf938f.png)
观察可以发现 他们都是一样的，这样就导致我 不管请求什么接口  都是有权操作的，请问  我还需要怎么修改 或者设置？
  初次使用 ，还望不灵赐教！

**Comment by stephenwang1011** [comment]
我好想明白了这个X-Authorization 要登录之后 自动生成之后复制过来当作session 来使用 是不是这样？
![image](https://user-images.githubusercontent.com/3350356/67403765-00212980-f5e5-11e9-8459-57e059693cd5.png)

**Comment by stephenwang1011** [comment]
这样权限就OK了，还希望作者评论一番
![image](https://user-images.githubusercontent.com/3350356/67403860-1fb85200-f5e5-11e9-909f-2549735e8cad.png)

**Comment by rzte** [comment]
是的，这里的录入实际就是录入关键的认证信息
